name: Release PyPI Package

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ GITHUB_SHA }}
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.5
    - name: Build package
      run: |
        poetry install
        poetry build
